
var divUpload,divProgress,divProgressBar,divGrid;var formUpload;var spanStatus,spanTransferred,spanElapsedTime,spanEstimatedTimeLeft,spanTransferRate,spanFileCountText;var inputCurrentFile,imgCurrentFile;var buttonAdd,buttonNewUpload,buttonClose,buttonCancel,buttonUpload,buttonRemove,buttonRemoveAll;var uploadID;var uploadCancel,uploadInProgress;var table,tBody;var formAction;var firstUpdate;var refreshFolder;var grid,buttonAddPos,lastFileInput,extensionIcons,allowedFileTypes,quotaSize,remainingQuotaSize;var reFileTypes;var ajaxUpload;var uploadStartTime;function SwfUploadHandler(){}
SwfUploadHandler.swfUpload=null;SwfUploadHandler.isLoaded=false;SwfUploadHandler.sessionTimerID=0;SwfUploadHandler.load=function(){SwfUploadHandler.swfUpload=new SWFUpload({flash_url:parent.resolveControlUrl("scripts/swfupload/swfupload.swf"),file_types:allowedFileTypes.value,file_types_description:"",swfupload_loaded_handler:SwfUploadHandler.onLoaded,file_queued_handler:SwfUploadHandler.onFileQueued,file_dialog_complete_handler:SwfUploadHandler.onFileDialogComplete,upload_start_handler:SwfUploadHandler.onUploadStart,upload_progress_handler:SwfUploadHandler.onUploadProgress,upload_error_handler:SwfUploadHandler.onUploadError,upload_success_handler:SwfUploadHandler.onUploadSuccess,upload_complete_handler:SwfUploadHandler.onUploadComplete,button_placeholder_id:"spanButtonPlaceholder",button_width:1,button_height:1,button_window_mode:SWFUpload.WINDOW_MODE.TRANSPARENT});}
SwfUploadHandler.onLoaded=function(){SwfUploadHandler.swfUpload.setButtonDimensions(buttonAdd.offsetWidth,buttonAdd.offsetHeight);SwfUploadHandler.isLoaded=true;SwfUploadHandler.quotaSize=(+quotaSize.value);SwfUploadHandler.remainingQuotaSize=(+remainingQuotaSize.value);grid.clear();var groupColumn=grid.addColumn("ID","CaseInsensitiveString");groupColumn.hidden=true;grid.addColumn(parent.language.getString("223"),"CaseInsensitiveString",false,null,parent.grid.columns[1].size);grid.addColumn(parent.language.getString("225"),"CaseInsensitiveString",false,null,parent.grid.columns[3].size);grid.addColumn(parent.language.getString("224"),"Number",true,null,parent.grid.columns[2].size);grid.addColumn("FullFileName","CaseInsensitiveString").hidden=true;grid.rowTitleColumn=grid.columns[1];if(parent.controlShowFileExtensions)
grid.columns[1].formatFunction=getNameWithoutExtension;grid.columns[3].formatFunction=formatSize;grid.sort(grid.columns[0]);grid.render(divGrid);updateUIState();while(formUpload.firstChild){formUpload.removeChild(formUpload.firstChild);}
buttonUpload.onclick=function(e){SwfUploadHandler.totalSize=0;SwfUploadHandler.uploadedSize=0;for(var j=0;j<grid.rows.length;j++)
SwfUploadHandler.totalSize+=grid.rows[j].cells[3];if(SwfUploadHandler.remainingQuotaSize>-1&&SwfUploadHandler.totalSize>SwfUploadHandler.remainingQuotaSize){alert(parent.language.getString("308",formatSize(SwfUploadHandler.totalSize),formatSize(SwfUploadHandler.remainingQuotaSize),formatSize(SwfUploadHandler.quotaSize)));return;}
showDivProgress();firstUpdate=true;SwfUploadHandler.currentFileIndex=1;SwfUploadHandler.startTime=(new Date()).getTime();var currentFileID=grid.rows[SwfUploadHandler.currentFileIndex-1].cells[0];updateStatus(0);SwfUploadHandler.groupID=createUniqueID();SwfUploadHandler.swfUpload.startUpload(currentFileID);SwfUploadHandler.sessionTimerID=setInterval("SwfUploadHandler.keepSessionAlive()",30000);};buttonCancel.onclick=function(e){SwfUploadHandler.swfUpload.cancelUpload(SwfUploadHandler.currentFile.id);SwfUploadHandler.currentFileIndex=grid.rows.length;};}
SwfUploadHandler.onFileQueued=function(file){var fileFullName=file.name;var fileName="";var fileExtension="";for(var j=0;j<grid.rows.length;j++){if(grid.rows[j].cells[4]==fileFullName){alert(parent.language.getString("312",fileFullName));return;}}
fileName=getNameWithoutExtension(fileFullName);fileExtension=getExtension(fileFullName);var typeDescription;if(fileExtension=="")
typeDescription=parent.language.getString("316");else
typeDescription=parent.language.getString("317",fileExtension.toUpperCase());var fileExtensionIcon=(extensionIcons.value.indexOf("("+fileExtension.toUpperCase()+")")==-1)?"unknown.png":fileExtension+".png"
var row=grid.addRow([file.id,fileName,typeDescription,file.size,fileFullName],fileExtensionIcon);row.render(grid.tbody);}
SwfUploadHandler.onFileDialogComplete=function(selectedFilesCount,queuedFilesCount){divGrid.scrollTop=divGrid.scrollHeight;updateUIState();}
SwfUploadHandler.onUploadStart=function(file){SwfUploadHandler.currentFile=file;var uploadURL;if(grid.rows.length==1){uploadURL=formAction+encodeURIComponent(SwfUploadHandler.groupID);}else{uploadURL=formAction+"&groupID="+encodeURIComponent(SwfUploadHandler.groupID);if(SwfUploadHandler.currentFileIndex==1)
uploadURL+="&groupOrder=first";else if(SwfUploadHandler.currentFileIndex==grid.rows.length)
uploadURL+="&groupOrder=last";}
uploadURL+="&UploadMethod=Flash";SwfUploadHandler.swfUpload.setUploadURL(uploadURL);}
SwfUploadHandler.onUploadProgress=function(file,uploadedSize,totalSize){updateStatus(1,SwfUploadHandler.currentFileIndex,grid.rows.length);var elapsedSeconds=((new Date()).getTime()-SwfUploadHandler.startTime)/1000;updateProgress(file.name,SwfUploadHandler.uploadedSize+uploadedSize,SwfUploadHandler.totalSize,elapsedSeconds);}
SwfUploadHandler.onUploadError=function(file,errorCode,message){if(errorCode==SWFUpload.UPLOAD_ERROR.FILE_CANCELLED){updateStatus(3);}else{updateStatus(4);var parameter;parameter="uploadID="+encodeURIComponent(SwfUploadHandler.groupID);parameter+="&cancel=0";XmlRequest("POST","filevista.asmx/GetUploadProgress",parameter,function complete(xmlHttp){SwfUploadHandler.onUploadErrorXmlComplete(xmlHttp,message);},function error(statusText){SwfUploadHandler.onUploadErrorXmlError(statusText,message);},parent.controlDebug);}
SwfUploadHandler.currentFileIndex=grid.rows.length;clearInterval(SwfUploadHandler.sessionTimerID);}
SwfUploadHandler.onUploadSuccess=function(file,serverData){if(SwfUploadHandler.currentFileIndex==grid.rows.length)
updateStatus(2);var result=trim(serverData);if(result.substring(0,15)!="UPLOAD_COMPLETE"){updateStatus(4);alert(result);parent.setTimeout("executeCommand(\"Refresh\")",0);}}
SwfUploadHandler.onUploadComplete=function(file){if(SwfUploadHandler.currentFileIndex==grid.rows.length){SwfUploadHandler.remainingQuotaSize-=SwfUploadHandler.totalSize;buttonCancel.style.display="none";buttonNewUpload.style.display="inline";buttonClose.style.display="inline";clearInterval(SwfUploadHandler.sessionTimerID);if(refreshFolder)
parent.setTimeout("executeCommand(\"Refresh\")",0);}else{SwfUploadHandler.currentFileIndex++;SwfUploadHandler.uploadedSize+=file.size;var nextFileID=grid.rows[SwfUploadHandler.currentFileIndex-1].cells[0];SwfUploadHandler.swfUpload.startUpload(nextFileID);}}
SwfUploadHandler.keepSessionAlive=function(){XmlRequest("POST","filevista.asmx/KeepSessionAlive","",function(xmlHttp){},function(statusText){},parent.controlDebug);}
SwfUploadHandler.onUploadErrorXmlComplete=function(xmlHttp,swfUploadMessage){var xmlDoc=xmlHttp.responseXML;var status,errorText;var uploadProgressNode=xmlDoc.getElementsByTagName("UploadProgress")[0];if(uploadProgressNode){status=(+uploadProgressNode.getAttribute("status"));errorText=uploadProgressNode.getAttribute("error");if(status==4)
alert(parent.language.getString("300")+"\n\n"+errorText);else if(status==-1)
alert(parent.language.getString("300")+"\n\n"+swfUploadMessage);}}
SwfUploadHandler.onUploadErrorXmlError=function onXmlError(statusText,swfUploadMessage){alert(parent.language.getString("300")+"\n\n"+swfUploadMessage);}
function onPageLoad(refresh){if(parent.ModalDialog)parent.ModalDialog.fitToContent(document);divUpload=document.getElementById("divUpload");divProgress=document.getElementById("divProgress");divProgressBar=document.getElementById("divProgressBar");divGrid=document.getElementById("divGrid");formUpload=document.getElementById("formUpload");spanStatus=document.getElementById("spanStatus");spanTransferred=document.getElementById("spanTransferred");spanElapsedTime=document.getElementById("spanElapsedTime");spanEstimatedTimeLeft=document.getElementById("spanEstimatedTimeLeft");spanTransferRate=document.getElementById("spanTransferRate");inputCurrentFile=document.getElementById("inputCurrentFile");buttonAdd=document.getElementById("buttonAdd");buttonNewUpload=document.getElementById("buttonNewUpload");buttonClose=document.getElementById("buttonClose");buttonCancel=document.getElementById("buttonCancel");buttonUpload=document.getElementById("buttonUpload");buttonRemove=document.getElementById("buttonRemove");buttonRemoveAll=document.getElementById("buttonRemoveAll");extensionIcons=document.getElementById("extensionIcons");allowedFileTypes=document.getElementById("allowedFileTypes");quotaSize=document.getElementById("quotaSize");remainingQuotaSize=document.getElementById("remainingQuotaSize");spanFileCountText=document.getElementById("spanFileCountText");imgCurrentFile=document.getElementById("imgCurrentFile");formUpload.target="frameUpload";formAction=formUpload.action;addEvent(document.body,"contextmenu",cancelEvent);addEvent(document.body,"selectstart",cancelEvent);addEvent(document.body,"dragstart",cancelEvent);refreshFolder=refresh;createGrid();if(document.getElementById("preConditionError").value!=""){buttonAdd.disabled=true;updateUIState();alert(document.getElementById("preConditionError").value);return;}
initFileChooser();switch(parent.controlUploadMethod){case"Flash":SwfUploadHandler.load();break;case"Ajax":ajaxUpload=(document.getElementById("ajaxUploadAvailable").value==1);break;case"Browser":ajaxUpload=false;break;}}
function startUpload(){try
{formUpload.removeChild(lastFileInput);uploadID=createUniqueID();formUpload.action=formAction+encodeURIComponent(uploadID);if(ajaxUpload)
formUpload.action+="&UploadMethod=Ajax";else
formUpload.action+="&UploadMethod=Browser";formUpload.submit();showDivProgress();uploadCancel=0;firstUpdate=true;uploadInProgress=true;uploadStartTime=(new Date()).getTime();setTimeout("getUploadProgress()",2000);}
catch(err)
{alert(parent.language.getString("302")+"\n\n"+err.message);}}
function getUploadProgress(){if(ajaxUpload){var parameter;parameter="uploadID="+encodeURIComponent(uploadID);parameter+="&cancel="+uploadCancel;XmlRequest("POST","filevista.asmx/GetUploadProgress",parameter,onUploadProgressXmlComplete,onXmlError,parent.controlDebug);}else{if(uploadInProgress){updateStatus(1,"-",grid.rows.length);var elapsedSeconds=((new Date()).getTime()-uploadStartTime)/1000;updateProgress("(no progress available, please wait)",0,0,elapsedSeconds);setTimeout("getUploadProgress()",1000);}}}
function onUploadProgressXmlComplete(xmlHttp){var xmlDoc=xmlHttp.responseXML;var uploadProgressNode=xmlDoc.getElementsByTagName("UploadProgress")[0];var status=0,totalSize=0,uploadedSize=0,elapsedSeconds=0;var fileName,fileNumber,filesCount;var xmlError=false,errorText;var statusText;if(!uploadProgressNode){status=4;xmlError=true;errorText=xmlHttp.responseText;}else{status=(+uploadProgressNode.getAttribute("status"));fileName=uploadProgressNode.getAttribute("fileName");fileNumber=uploadProgressNode.getAttribute("fileNumber");totalSize=(+uploadProgressNode.getAttribute("totalSize"));uploadedSize=(+uploadProgressNode.getAttribute("uploadedSize"));elapsedSeconds=(+uploadProgressNode.getAttribute("elapsedSeconds"));errorText=uploadProgressNode.getAttribute("error");if(uploadInProgress&&status<0)status=0;filesCount=grid.rows.length;}
updateStatus(status,fileNumber,filesCount);updateProgress(fileName,uploadedSize,totalSize,elapsedSeconds);if(status==0||status==1){setTimeout("getUploadProgress()",1000);}else{buttonCancel.style.display="none";buttonNewUpload.style.display="inline";buttonClose.style.display="inline";if(refreshFolder)
parent.setTimeout("executeCommand(\"Refresh\")",0);if(xmlError)
alert(parent.language.getString("301")+"\n\n"+errorText);else if(status==4){if(uploadInProgress){alert(parent.language.getString("300")+"\n\n"+errorText);uploadInProgress=false;}}}}
function updateStatus(status,fileNumber,filesCount){if(status<0)return;var statusText;switch(status){case 0:statusText=parent.language.getString(212);break;case 1:statusText=parent.language.getString(213)+" "+fileNumber+" / "+filesCount+"...";break;case 2:statusText=parent.language.getString(215);break;case 3:statusText=parent.language.getString(217);break;case 4:statusText=parent.language.getString(218);}
spanStatus.firstChild.nodeValue=statusText;}
function updateProgress(fileName,uploadedSize,totalSize,elapsedSeconds){if(fileName&&fileName!=""){inputCurrentFile.value=fileName;var fileExtension=getExtension(fileName);var fileExtensionIcon=(extensionIcons.value.indexOf("("+fileExtension.toUpperCase()+")")==-1)?"unknown.png":fileExtension+".png"
imgCurrentFile.src="images/fileicons/"+fileExtensionIcon;imgCurrentFile.style.visibility="visible";}
else{inputCurrentFile.value="";imgCurrentFile.style.visibility="hidden";}
if(firstUpdate){divProgressBar.style.visibility="visible";firstUpdate=false;}
var percentage=(totalSize>0)?parseInt(uploadedSize/totalSize*100):0;if(percentage>100)percentage=100;var transferRate=(elapsedSeconds>0)?parseInt(uploadedSize/elapsedSeconds):0;var estimatedSecondsLeft=(transferRate>0)?(parseInt(totalSize/transferRate)-elapsedSeconds):0;divProgressBar.firstChild.style.width=percentage+"%";spanTransferred.firstChild.nodeValue=((uploadedSize>0)?(formatSize(uploadedSize)+" / "):"")+formatSize(totalSize)+" ("+percentage+" %)";spanElapsedTime.firstChild.nodeValue=String(new Date(0,0,0,0,0,elapsedSeconds)).match(/\S{8}/);spanEstimatedTimeLeft.firstChild.nodeValue=String(new Date(0,0,0,0,0,estimatedSecondsLeft)).match(/\S{8}/);if(transferRate>0)spanTransferRate.firstChild.nodeValue=formatSize(transferRate)+"/Sec";}
function onXmlError(statusText){alert(parent.language.getString("301")+"\n\n"+statusText);}
function cancelUpload(){if(frames["frameUpload"].stop)
frames["frameUpload"].stop();else
document.execCommand('Stop');uploadCancel=1;getUploadProgress();buttonCancel.disabled=true;}
function showDivProgress(){spanStatus.firstChild.nodeValue="\u00a0";inputCurrentFile.value="\u00a0";imgCurrentFile.style.visibility="hidden";divProgressBar.style.visibility="hidden";divProgressBar.firstChild.style.width="0px";spanTransferred.firstChild.nodeValue="\u00a0";spanElapsedTime.firstChild.nodeValue="\u00a0";spanEstimatedTimeLeft.firstChild.nodeValue="\u00a0";spanTransferRate.firstChild.nodeValue="\u00a0";buttonNewUpload.style.display="none";buttonClose.style.display="none";buttonCancel.style.display="inline";buttonCancel.disabled=false;divUpload.style.visibility="hidden";divProgress.style.visibility="visible";}
function showDivUpload(){imgCurrentFile.style.visibility="hidden";divProgressBar.style.visibility="hidden";divProgress.style.visibility="hidden";divUpload.style.visibility="visible";initFileChooser();}
function createGrid(){grid=new Grid();grid.imgAscending.src="images/ascending.png";grid.imgDescending.src="images/descending.png";grid.iconsPath="images/fileicons/";grid.setIconSize(16,16);var groupColumn=grid.addColumn("Order","Number");groupColumn.hidden=true;grid.addColumn(parent.language.getString("223"),"CaseInsensitiveString",false,null,parent.grid.columns[1].size);grid.addColumn(parent.language.getString("225"),"CaseInsensitiveString",false,null,parent.grid.columns[3].size);grid.addColumn("FullFileName","CaseInsensitiveString").hidden=true;grid.rowTitleColumn=grid.columns[1];if(parent.controlShowFileExtensions)
grid.columns[1].formatFunction=getNameWithoutExtension;grid.sort(grid.columns[0]);grid.render(divGrid);grid.onSelectionComplete=onSelectionComplete;buttonAddPos=findPosition(document.getElementById("buttonAdd"));if(!SwfUploadHandler.isLoaded){var fileTypes=allowedFileTypes.value.split(";");var reString="^\\b(";for(var i=0;i<fileTypes.length;i++){reString+=trim(fileTypes[i].replace(".","\\.").replace("*",".*"));if(i<fileTypes.length-1)reString+="|";}
reString+="\\b)$";reFileTypes=new RegExp(reString,"i");}}
function onFileChoose(fileInput){var filePath=fileInput.value;var fileFullName=filePath.substr(filePath.lastIndexOf("\\")+1,filePath.length);var fileName="";var fileExtension="";if(!reFileTypes.test(fileFullName)){alert(parent.language.getString("310",fileFullName,allowedFileTypes.value));return;}
for(var j=0;j<grid.rows.length;j++){if(grid.rows[j].cells[3]==fileFullName){formUpload.removeChild(fileInput);addFileInput();alert(parent.language.getString("312",fileFullName));return;}}
fileName=getNameWithoutExtension(fileFullName);fileExtension=getExtension(fileFullName);var typeDescription;if(fileExtension=="")
typeDescription=parent.language.getString("316");else
typeDescription=parent.language.getString("317",fileExtension.toUpperCase());var fileExtensionIcon=(extensionIcons.value.indexOf("("+fileExtension.toUpperCase()+")")==-1)?"unknown.png":fileExtension+".png"
var row=grid.addRow([fileInput,fileName,typeDescription,fileFullName],fileExtensionIcon);row.render(grid.tbody);divGrid.scrollTop=divGrid.scrollHeight;fileInput.style.left='-1000px';addFileInput();updateUIState();}
function addFileInput(){var fileInput=document.createElement('input');fileInput.type="file";fileInput.name="fileInput";fileInput.style.position="absolute";fileInput.style.zIndex="2";setOpacity(fileInput,0);fileInput.style.width='250px';fileInput.style.height=buttonAdd.offsetHeight+'px';fileInput.style.left=buttonAddPos[0]-160+'px';fileInput.style.top=buttonAddPos[1]-65+'px';fileInput.onchange=function(e){onFileChoose(fileInput);};formUpload.appendChild(fileInput);lastFileInput=fileInput;}
function removeSelected(){if(SwfUploadHandler.isLoaded){for(var key in grid.selectedRows){grid.removeRow(grid.selectedRows[key]);}}else{for(var key in grid.selectedRows){formUpload.removeChild(grid.selectedRows[key].cells[0]);grid.removeRow(grid.selectedRows[key]);}}
updateUIState();}
function initFileChooser(){if(!SwfUploadHandler.isLoaded){while(formUpload.firstChild){formUpload.removeChild(formUpload.firstChild);}
addFileInput();}
grid.removeAllRows();updateUIState();}
function onSelectionComplete(e){buttonRemove.disabled=(grid.selectedCount>0)?false:true;}
function updateUIState(){buttonRemove.disabled=(grid.selectedCount>0)?false:true;buttonRemoveAll.disabled=(grid.rows.length>0)?false:true;buttonUpload.disabled=(grid.rows.length>0)?false:true;if(grid.rows.length==0){if(!grid.sortColumn.hidden)grid.sortColumn.cellElement.removeChild(grid.imgOrder);grid.sortColumn=grid.columns[0];}
spanFileCountText.innerHTML=parent.language.getString("228","<b>"+grid.rows.length+"</b>");}
function checkUploadResult(){if(!uploadInProgress)return;try{var frameUpload=window.frames["frameUpload"];var result=trim(frameUpload.document.body.innerText||frameUpload.document.body.textContent);if(result.substring(0,15)=="UPLOAD_COMPLETE"){if(!ajaxUpload){var totalSize=result.split("|")[1];updateStatus(2);var elapsedSeconds=((new Date()).getTime()-uploadStartTime)/1000;updateProgress("",totalSize,totalSize,elapsedSeconds);buttonCancel.style.display="none";buttonNewUpload.style.display="inline";buttonClose.style.display="inline";if(refreshFolder)
parent.setTimeout("executeCommand(\"Refresh\")",0);}}else{updateStatus(4);alert(frameUpload.document.title||frameUpload.document.body.innerText||frameUpload.document.body.textContent);buttonCancel.style.display="none";buttonNewUpload.style.display="inline";buttonClose.style.display="inline";parent.setTimeout("executeCommand(\"Refresh\")",0);}
uploadInProgress=false;}
catch(err){}}